### ISSUE TITLE
`mysqlclient` library uses static path

### ISSUE THREAD

**Issue by lpetre-ulb** [lmoureaux/cmsgemos#1]
The MySQL client library is searched through `mysql_config`, but the `IMPORTED_LOCATION` is set to a static path which might not exists (e.g. Archlinux). Moreover, there are no checks that the command exists.

https://github.com/lmoureaux/cmsgemos/blob/ffb9699e50ab06400c38b4c31c5b4727769c2be4/CMakeLists.txt#L68-L77

The search for the MySQL client library should be robustly performed.

**Comment by lmoureaux** [comment]
Kexi has [a BSD-licensed implementation](https://github.com/KDE/kdb/blob/master/cmake/modules/FindMySQL.cmake). Let's add it to `gembuild`.
