### ISSUE TITLE
`htdocs` are always installed in the root filesystem

### ISSUE THREAD

**Issue by lpetre-ulb** [lmoureaux/cmsgemos#2]
The `CMakeLists.txt`'s always install the `htdocs` in `/opt/xdaq/htdocs`. For example in `gemonlinedb` : https://github.com/lmoureaux/cmsgemos/blob/bf349ca969ae759116cf6151901b544aabda4658/gemonlinedb/CMakeLists.txt#L58

If the target directory is not user-writable, the installation fails. Moreover, it is possible to compile `xDAQ` to be installed in other paths. In particular, the superbuild fails because it expects all the files (including the `htdocs`) to be installed in a user configurable directory.

Although it can be worked-around with `DESTDIR`, it is not the canonical way of doing things. One could expected that the prefix is respected for all files or, at least, that the target directory for the `htdocs` is configurable.

**Comment by lmoureaux** [comment]
The files go into the xDAQ install tree, and I'm not 100% sure they can be moved outside. The default should depend on the xDAQ location.

If the files *can* actually be moved out of the xDAQ tree, their location should be made configurable.

**Comment by lpetre-ulb** [comment]
I think you are right, the files must, more than probably, go into the xDAQ install tree. I'm not really sure what is the best way to handle this if xDAQ is not installed in its standard location.

Maybe, a supplementary variable could be returned by `FindxDAQ.cmake` and then used for this purpose. In any case, assuming the standard installation tree for xDAQ seems to be a mistake.

**Comment by lmoureaux** [comment]
HTML files are now installed in `share/cmsgemos/htdocs`, which contains symlinks to the contents of the original xDAQ directory.
