### ISSUE TITLE
`gempython` installation fails

### ISSUE THREAD

**Issue by lpetre-ulb** [lmoureaux/cmsgemos#3]
The `add_cmsgemos_module` tries to install the `include/gem` directory : https://github.com/lmoureaux/cmsgemos/blob/bf349ca969ae759116cf6151901b544aabda4658/CMakeLists.txt#L101

However, the directory does not exist for `gempython` and so the installation fails. I would expect the installation to succeed. This could be resolved either in `add_cmsgemos_module` or in the `gempython` `CMakeLists.txt`.

**Comment by lmoureaux** [comment]
Fixed in f151568
